#.travis.yml
language: node_js
node_js:
  - "12.16.1"
branches:
only:
  - master
before_script:
script:
    - npm --v
after_success:
    - ./deploy.sh
notifications:
  email: jordisabadell@gmail.com
  on_failure: always
  on_success: always