#.travis.yml
language: node_js
node_js:
  - "12.16.1"
branches:
only:
  - master
before_script:
script:
    - npm --v
after_success:
    - curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://ftp.kilometresolidari.cat/public_html
notifications:
  email: jordisabadell@gmail.com
  on_failure: always
  on_success: always